name: oop2
recipe: lamp

proxy:
  appserver:
    - oop2.lndo.site
  pma:
    - phpmyadmin.lndo.site

config:
  php: '7.3'
  via: apache
  webroot: .
  xdebug: true

services:
  appserver:
    ports:
      - '8080:80'
  database:
    type: mariadb      
    creds:
      user: lamp
      password: lamp
      database: lamp
  pma:
    type: phpmyadmin      

